### ISSUE TITLE
Referneces to api.kustomize.io

### ISSUE THREAD

**Issue by MyIgel** [replicatedhq/kustomize-demo#3]
This repo references [api.kustomize.io](https://github.com/replicatedhq/kustomize-demo/blob/main/src/App.js#L10) which seems to do the main work of this app, is that endpoint eventually also available somewhere?

Eventually @marccampbell? ;)

**Comment by marccampbell** [comment]
Oops: https://github.com/replicatedhq/kustomize-demo-api. (it's now public).

This repo will be Apache2, working with our team to add appropriate licenses to these repos.

**Comment by MyIgel** [comment]
Thx! I'll dig deeper ^^
